/**
 * faucet.ts — Phase 4: claim BEES from the Habitra testnet faucet.
 *
 *   Faucet.claim()  (one claim of 10 BEES per wallet, initiated by the user)
 *
 * SECURITY BOUNDARY (do not break this)
 * -------------------------------------
 * No private key, seed phrase or signing secret is ever created, imported,
 * stored or transmitted. The claim goes through `createBrowserWalletClient`
 * (`custom(window.ethereum)`): viem only asks the user's wallet extension to
 * sign and receives the transaction hash back. The faucet contract itself
 * never mints — it transfers BEES it already holds (funded by the BEES owner).
 *
 * The call is simulated before it is sent, so an already-claimed revert
 * (FaucetEmpty / AlreadyClaimed) is surfaced to the UI before any gas is spent.
 *
 * The existing ABIs (lib/contracts/abi.ts) are reused as-is — the faucet ABI is
 * generated by `contracts/scripts/export-abis.js`, not hand-written here.
 */

import { isAddress, parseUnits, type Address, type Hash } from 'viem';

import { habitraBeesFaucetAbi } from '../contracts/abi';
import { api } from '../http';
import { BEES_DECIMALS } from './bees';
import { createBrowserPublicClient, createBrowserWalletClient } from './injectedWallet';

/** Claim amount: 10 BEES expressed in 18-decimal base units. */
export const FAUCET_CLAIM_BASE_UNITS: bigint = parseUnits('10', BEES_DECIMALS);

/** Human-facing label so the UI never has to re-derive the amount. */
export const FAUCET_CLAIM_LABEL = '10 BEES';

type BrowserPublicClient = NonNullable<ReturnType<typeof createBrowserPublicClient>>;

/** Narrows a configured contract address, failing loudly when it is missing. */
function requireAddress(value: string | null | undefined, message: string): Address {
  if (!value || !isAddress(value)) {
    throw new Error(message);
  }
  return value;
}

/**
 * Read whether `account` has already claimed from the faucet.
 *
 * Used so the UI can disable the button and explain the state before the user
 * ever signs. Returns false when the faucet address is missing.
 */
export async function readFaucetClaimed(
  faucetAddress: string | null | undefined,
  account: Address,
): Promise<boolean> {
  const faucet = requireAddress(faucetAddress, 'Faucet address is not configured.');
  const client = createBrowserPublicClient();
  if (!client) return false;

  return client.readContract({
    address: faucet,
    abi: habitraBeesFaucetAbi,
    functionName: 'hasClaimed',
    args: [account],
  });
}

/**
 * Wait for a claim transaction the user just signed and throw if it reverted, so
 * a reverted write is never reported as success.
 */
async function waitForSuccess(
  client: BrowserPublicClient,
  hash: Hash,
  label: string,
): Promise<void> {
  const receipt = await client.waitForTransactionReceipt({ hash });
  if (receipt.status !== 'success') {
    throw new Error(`${label} transaction reverted (${hash}).`);
  }
}

/**
 * Simulate, then send, then confirm `Faucet.claim()`.
 *
 * Resolves with the claim transaction hash once its receipt shows success.
 * Throws if the user rejects the prompt (EIP-1193 4001) or the call reverts
 * (already claimed / faucet empty).
 */
export async function claimBees(faucetAddress: string, account: Address): Promise<Hash> {
  const faucet = requireAddress(faucetAddress, 'Faucet address is not configured.');

  const publicClient = createBrowserPublicClient();
  const walletClient = createBrowserWalletClient(account);

  if (!publicClient || !walletClient) {
    throw new Error('No browser wallet is available to send the claim transaction.');
  }

  const { request } = await publicClient.simulateContract({
    account,
    address: faucet,
    abi: habitraBeesFaucetAbi,
    functionName: 'claim',
    args: [],
  });

  const hash = await walletClient.writeContract(request);
  await waitForSuccess(publicClient, hash, 'BEES claim');

  return hash;
}

/**
 * Server-side claim: ask the backend to distribute 10 BEES to the linked public
 * address. No browser-wallet signature is required to RECEIVE BEES — the backend
 * signs `claimFor()` with its own faucet-owner key. Resolves with the backend's
 * response (txHash, amount, recipient, claimed). Throws an ApiError on 400/403/
 * 409/500 so the UI can show the right state.
 */
export async function claimBeesServer(address: string) {
  return api.post<{
    txHash: string;
    amount: string;
    recipient: string;
    claimed: boolean;
  }>('/faucet/claim', { address });
}
